services:
  # Service PostgreSQL
  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clouds5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

  # Service de l'application .NET (MVC)
services:
  myapp:
    build: .
    ports:
      - "5123:5123"
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=clouds5
      - DB_USER=postgres
      - DB_PASSWORD=postgres

# Volume persistant pour PostgreSQL
volumes:
  postgres-data:
