services:
  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clouds5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  myapp:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - postgres-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=clouds5;Username=postgres;Password=postgres

volumes:
  postgres-data:
